"""create player and game tables

Revision ID: 899872eb1175
Revises:
Create Date: 2026-08-14 19:25:16.629684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "899872eb1175"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("lichess", "chess_com", name="chess_platform", native_enum=False),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "username", name="uq_players_platform_username"),
    )
    op.create_index(
        "ix_players_platform_username", "players", ["platform", "username"], unique=False
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("lichess", "chess_com", name="chess_platform", native_enum=False),
            nullable=False,
        ),
        sa.Column("external_game_id", sa.String(length=255), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "player_color",
            sa.Enum("white", "black", name="player_color", native_enum=False),
            nullable=True,
        ),
        sa.Column("opponent_username", sa.String(length=255), nullable=True),
        sa.Column("player_rating", sa.Integer(), nullable=True),
        sa.Column("opponent_rating", sa.Integer(), nullable=True),
        sa.Column("rating_change", sa.Integer(), nullable=True),
        sa.Column(
            "result",
            sa.Enum("win", "loss", "draw", name="game_result", native_enum=False),
            nullable=False,
        ),
        sa.Column("opening_name", sa.String(length=255), nullable=True),
        sa.Column("opening_eco", sa.String(length=10), nullable=True),
        sa.Column("number_of_moves", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("time_control", sa.String(length=50), nullable=True),
        sa.Column(
            "game_speed",
            sa.Enum(
                "bullet",
                "blitz",
                "rapid",
                "classical",
                "correspondence",
                "unknown",
                name="game_speed",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("rated", sa.Boolean(), nullable=True),
        sa.Column("termination", sa.String(length=100), nullable=True),
        sa.Column("pgn", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0",
            name="ck_games_duration_seconds_nonneg",
        ),
        sa.CheckConstraint(
            "number_of_moves IS NULL OR number_of_moves >= 0",
            name="ck_games_number_of_moves_nonneg",
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform",
            "external_game_id",
            "player_id",
            name="uq_games_platform_external_game_id_player",
        ),
    )
    op.create_index("ix_games_game_speed", "games", ["game_speed"], unique=False)
    op.create_index("ix_games_opening_name", "games", ["opening_name"], unique=False)
    op.create_index(
        "ix_games_player_id_played_at", "games", ["player_id", "played_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_games_player_id_played_at", table_name="games")
    op.drop_index("ix_games_opening_name", table_name="games")
    op.drop_index("ix_games_game_speed", table_name="games")
    op.drop_table("games")
    op.drop_index("ix_players_platform_username", table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
